#!/usr/bin/bash

set -e

rama_actual=$(git symbolic-ref --short HEAD)

if [ $rama_actual == "main" ]; then
    echo "Rama actual es '$rama_actual', ejecutando deploy_all.sh"
    ./scripts/deploy_all.sh
else
    echo "Merge realizado en $rama_actual, no se ejecuto deploy_all.sh"
    exit 0
fi